### PR TITLE
Utf8

### PR DESCRIPTION
**Pull request by casid**
Hi @agentgt this PR includes the performance optimizations done in jte 3. I also upgraded all other template engines to their latest version.

I don't quite understand what happened to `StringGetBytesUtf8`, which performed a lot better in your last run.

### CODE REVIEW

**Comment by agentgt** [comment]
Thanks I’ll have to see.

I’m surprised rocker surpassed jstachio but I will say it at this point it largely comes down to getting pre allocating right and making the actual template smaller.

I’m not sure if you changed your template but noticed it had different character count and I meant to fix that (I think spaces were used instead of tabs).

**Comment by agentgt** [comment]
Ignore the fat finger close.

**Comment by agentgt** [comment]
Did you see utf8.sh ?

You need to pass the `-Dbenchmark.utf8=true` when you run the benchmark otherwise it is just latin1 aka mostly ascii.

I ran the test with utf8.sh and I still get better results (ie JStachio winning) but I'm on a macbook intel and macbook arm. I never tested windows and I suspect you use it based on your line endings in source.

I don't have access to the Arm machine as I'm on vacation but I will check in old macbook intel machine  results now.

**Comment by agentgt** [comment]
I pulled your changes I'm not sure how you got your original results. It has to be Windows difference. 

I just checked in my old macbook early 2015 results.

I have some cloud machines crunching it now but so far on macs JStachio is faster and by the looks of the giant google cloud machines are showing even more compelling results. 

This is JDK 18 on my macbook. 

I will try with JDK 17 on the cloud machines and 20 as well later.

**Comment by agentgt** [comment]
The `StringGetBytes` is kind of a bug I think. I'm not sure why it so slow for me as well. I think we changed something on 1.1.0 where it using OutputStreamWriter IIRC. So that is a good find!

**Comment by agentgt** [comment]
Yeah apparently I made a mistake on code generation somewhere in 1.1 with regular string output where it calls the property methods for the escaper and formatter. Apparently those three method calls make a difference.

Anyway I updated the code to call the static method directly:

https://github.com/agentgt/template-benchmark/commit/5752c89cab4cdf2fe31ddccf700c3a667756879f

```
Benchmark                      Mode  Cnt       Score        Error  Units
JStachioUtf8.benchmark        thrpt    3  139711.714 ±  30551.813  ops/s
JteUtf8.benchmark             thrpt    3  124732.235 ±   7287.045  ops/s
RockerUtf8.benchmark          thrpt    3  105550.890 ± 206298.620  ops/s
StringGetBytesUtf8.benchmark  thrpt    3  146540.836 ±  34659.487  ops/s
```

The above is no utf-8 characters but assuming there are (ie use pre-encoding regardless).

**Comment by agentgt** [comment]
@casid thank you so much for rerunning the tests and messaging me as you found some good bugs I need to fix on code generation.

I think we need to make a docker image next to make it easier to test on linux.

**Comment by casid** [comment]
Yes, I've been running the benchmarks according to utf8.sh.

The results are on Windows/AMD Ryzen 5950x. On my 2015 Macbook I get similar results to you.

Macbook 2015
```
"Benchmark","Mode","Threads","Samples","Score","Score Error (99,9%)","Unit"
"com.mitchellbosecke.benchmark.utf8.JStachioUtf8.benchmark","thrpt",16,3,"228009,907666","52167,012914","ops/s"
"com.mitchellbosecke.benchmark.utf8.JteUtf8.benchmark","thrpt",16,3,"201423,600790","72860,459947","ops/s"
"com.mitchellbosecke.benchmark.utf8.RockerUtf8.benchmark","thrpt",16,3,"192327,518627","153837,944082","ops/s"
"com.mitchellbosecke.benchmark.utf8.StringGetBytesUtf8.benchmark","thrpt",16,3,"112338,820296","2547,567212","ops/s"
```

AMD Ryzen
```
"Benchmark","Mode","Threads","Samples","Score","Score Error (99,9%)","Unit"
"com.mitchellbosecke.benchmark.utf8.JStachioUtf8.benchmark","thrpt",16,3,"601418,193519","193647,070286","ops/s"
"com.mitchellbosecke.benchmark.utf8.JteUtf8.benchmark","thrpt",16,3,"790805,562527","27988,111586","ops/s"
"com.mitchellbosecke.benchmark.utf8.RockerUtf8.benchmark","thrpt",16,3,"679482,660306","59955,099316","ops/s"
"com.mitchellbosecke.benchmark.utf8.StringGetBytesUtf8.benchmark","thrpt",16,3,"180722,717869","48385,300305","ops/s"
```

It looks like the memory access of ArrayOfByteArrays Style is faster on my Windows machine, while writing directly to a Byte Array is faster on my Macbook. I'm curious to see what my M1 Macbook at work is doing here.

**Comment by agentgt** [comment]
@casid I had a little time today... and honestly I have no idea what is going on.

For macOS it appears the byte growing approach is faster. For linux they are about even. However for Windows the "chunking" or pseudo linked list style is faster.

I will say the reason I picked the byte growing array approach is because it benchmarked the fastest on techempower probably because it is easier to thread local or use shared pooling.

Also the number of non-latin characters seems to make a difference as well. The more ascii like the faster byte arrays work.

I think we could probably come up with some sort of shared utility library for output across templating languages. Maybe even one that detects platform and memory and chooses the better algorithm.

**Comment by agentgt** [comment]
@casid When you get a chance can you pull the utf-8 branch and try on your windows machine?

I made some changes where I abstracted out the three main cpu saving outputs:

* Chunk - which is what JTE and Rocker use which is a list of arrays
* Array - which is basically a growing array like ByteArrayOutputstream. This is what JStachio uses. It is notable in that it is the only one that can reuse allocation via threadlocal but this test does not do that.
* Deque - Like chunk but Guava and Spring use a Deque

**Comment by casid** [comment]
> I think we could probably come up with some sort of shared utility library for output across templating languages. Maybe even one that detects platform and memory and chooses the better algorithm.

I'm not sure this is a good idea, at least for jte. There's more to it than raw CPU speed. There's also memory allocations and that is where the chunking style really shines. I think it is important, that the user gets consistent behavior on all platforms.

In the case of jte, `Utf8ByteOutput` is usually not used with a `toByteArray`. That was added because the UTF-8 benchmark created byte arrays to compare performance. The usual scenario is like this:

```java
Utf8ByteOutput output = new Utf8ByteOutput();

// Rendering will allocate only small byte arrays for user output and grow the array list as needed.
// This uses barely any memory.
// Still, in case of a rendering error, no uncomplete response is sent to the user.
templateEngine.render(page.getTemplate(), page, output);

// We know about the content length at no additional cost.
exchange.sendResponseHeaders(200, output.getContentLength());

// The output is streamed to the client
try (OutputStream os = new BufferedOutputStream(exchange.getResponseBody())) {
   output.writeTo(os);
}
```

> When you get a chance can you pull the utf-8 branch and try on your windows machine?

I'll have a look at it in the next days!

**Comment by agentgt** [comment]
> I'm not sure this is a good idea, at least for jte. There's more to it than raw CPU speed. There's also memory allocations and that is where the chunking style really shines. I think it is important, that the user gets consistent behavior on all platforms.

Yeah I was jumping the gun on this but I will tell you it is fucking inconsistent regardless. I mean the massive difference between operating system, hardware (arm vs intel), and cores vs threads seems to make a big difference.

I have an action on github that creates the benchmark images as an artifact (example): 
https://github.com/agentgt/template-benchmark/actions/runs/5396291210

files:
https://github.com/agentgt/template-benchmark/suites/13912454283/artifacts/774162391

On various machines particularly Mac and Linux Arm I have tested JStachio runs faster and Array/Deque  runs fastest (regardless of algorithm) but in the above Rocker runs faster and seems to consistently run faster on low powered Linux Intel machines

If anything the output algorithms seem to be the most consistent part of the whole thing. I was just saying offering all three options somewhere. Whether that is just included in the templating library (copy 'n paste) or as a separate library is not really that important at the moment.

> In the case of jte, Utf8ByteOutput is usually not used with a toByteArray. That was added because the UTF-8 benchmark created byte arrays to compare performance. The usual scenario is like this:

Again I used `toByteArray` because it is the same for all the algorithms. When you copy something to an OutputStream it is more or less the same. And while the `OutputStream` (which requires set content-length first which requires buffering anyway!) is the common denominator for blocking algorithms it is not for non-blocking. Besides most of the frameworks turn it back into byte array otherwise it becomes `Transfer-Encoding: chunked` encoding which is highly discouraged for HTML output.

BTW the chunk/deque approach have drawbacks in that buffers cannot be reused nor is it as easy to preallocate (preallocating a list of pointers isn't the same as preallocating an array).

That is right... preallocating correctly is the game here (especially if we want to talk about consistency) and when you do:

```
exchange.sendResponseHeaders(200, output.getContentLength());
try (OutputStream os = new BufferedOutputStream(exchange.getResponseBody())) {
```

The framework has to be smart enough to preallocate based on the `output.getContentLength()` and many do.

For example in a nonblocking world instead of acquiring an `OutputStream` you acquire a buffer like:

https://github.com/jstachio/jstachio/blob/385d21f4a707dc202281d8e4a3c88c15c03b5712/opt/jstachio-spring-webflux/src/main/java/io/jstach/opt/spring/webflux/JStachioEncoder.java#L143C3-L143C101

```
DataBufferOutput output = new DataBufferOutput(bufferFactory.allocateBuffer(bufferSize), charset);
```

N.B. the bufferSize.


> I'll have a look at it in the next days!

Thanks I just don't have a beefy windows machine these days so I'm curious what the results are. 

All things considered this is mainly a curious exploration of what/how different platforms JIT optimize.

**Comment by casid** [comment]
> Besides most of the frameworks turn it back into byte array...

I'm not sure about this. TCP packets are small. It would make sense to send a response to the client without allocating a big byte array (since it cannot be sent in one packet anyway).

But I think we are at a level of micro optimization, no one cares about in reality.

I ran the latest revision of your branch on my windows machine:

ascii
```
Benchmark                     (output)   Mode  Cnt       Score        Error  Units
JStachioUtf8.benchmark           ARRAY  thrpt    3  455925,602 ±  25054,591  ops/s
JStachioUtf8.benchmark           CHUNK  thrpt    3  781110,036 ± 177557,646  ops/s
JteUtf8.benchmark                ARRAY  thrpt    3  514758,292 ± 102894,083  ops/s
JteUtf8.benchmark                CHUNK  thrpt    3  833514,075 ± 124920,700  ops/s
RockerUtf8.benchmark             ARRAY  thrpt    3  548758,806 ± 105941,110  ops/s
RockerUtf8.benchmark             CHUNK  thrpt    3  935468,843 ± 310887,523  ops/s
StringGetBytesUtf8.benchmark       N/A  thrpt    3  626698,269 ±  25559,992  ops/s

```

utf8
```
Benchmark                     (output)   Mode  Cnt       Score        Error  Units
JStachioUtf8.benchmark           ARRAY  thrpt    3  438980,164 ±  27766,196  ops/s
JStachioUtf8.benchmark           CHUNK  thrpt    3  731944,877 ±  50222,507  ops/s
JteUtf8.benchmark                ARRAY  thrpt    3  487741,743 ±  56991,090  ops/s
JteUtf8.benchmark                CHUNK  thrpt    3  782866,982 ± 102957,915  ops/s
RockerUtf8.benchmark             ARRAY  thrpt    3  497101,323 ± 373272,304  ops/s
RockerUtf8.benchmark             CHUNK  thrpt    3  862945,528 ±  24055,633  ops/s
StringGetBytesUtf8.benchmark       N/A  thrpt    3  173342,811 ± 113353,111  ops/s

```

**Comment by agentgt** [comment]
There is a bug in the jstachio benchmark. I accidentally create the output twice lol:
https://github.com/agentgt/template-benchmark/blob/106935729935d416d035a61bce43db222cdd04c2/src/main/java/com/mitchellbosecke/benchmark/utf8/JStachioUtf8.java#L41

Anyway thanks for getting that to me! I should hopefully get windows working on the github actions soon:

https://github.com/agentgt/template-benchmark/actions/runs/5405762501

If you take a look at those which are running on github runners the ARRAY one outperforms CHUNK for both Linux and MacOS.

Its like it is completely inverted. It's very bizarre. I do expect quite a bit of variance but not completely different behavior like that on different platforms.

JStachio, JTE, Rocker rotate back and forth. Rocker has a weird advantage purely in that it runs last. I tested that by moving the order around a little. As far my testing goes all three appear to be equal especially when error considerations are had and only vary a little by platform but the ARRAY and CHUNK... that is weird.

> I'm not sure about this. TCP packets are small. It would make sense to send a response to the client without allocating a big byte array (since it cannot be sent in one packet anyway).

That would only make since if we were doing nonblocking or stream encoding (ie `Encoding: chunked`) and even the nonblocking ones do it as buffering is easier for backpressure reasons.

I know this because I spent a fair amount of time on Jooby and Techempower benchmarks and looked at how undertow, jetty, and netty work. Each of them have buffer abstractions but most of them will take a byte array. 

If you are using threadlocals (which most of the top ones do) then you can reuse the byte array (assuming you don't need to resize).

Unless you specifically ask the web framework to stream it will not stream. It will buffer or write to a temp file and then serve it when you using OutputStream. 

Besides we are talking about HTML in 2023 not giant files and templating engines are not at the level of TCP. 

Anyway yeah most of this doesn't matter for most users but I am still curious about the CHUNK/ARRAY difference.

Again thanks for getting back to me!

**Comment by casid** [comment]
This has nothing to do with `Encoding: chunked`. The cool thing is we **can** send the Content-length Header! Here's Jetty's `HttpOutput`, which is their `OutputStream` implementation:

```java
@Override
    public void write(byte[] b, int off, int len) throws IOException
    {
        if (LOG.isDebugEnabled())
            LOG.debug("write(array {})", BufferUtil.toDetailString(ByteBuffer.wrap(b, off, len)));

        boolean last;
        boolean aggregate;
        boolean flush;

        // Async or Blocking ?
        boolean async;
        synchronized (_channelState)
        {
            checkWritable();
            long written = _written + len;
            int space = maximizeAggregateSpace();
            last = _channel.getResponse().isAllContentWritten(written);
            // Write will be aggregated if:
            //  + it is smaller than the commitSize
            //  + is not the last one, or is last but will fit in an already allocated aggregate buffer.
            aggregate = len <= _commitSize && (!last || BufferUtil.hasContent(_aggregate) && len <= space);
            flush = last || !aggregate || len >= space;

// ...

        // Blocking write
        try
        {
            // flush any content from the aggregate
            if (BufferUtil.hasContent(_aggregate))
            {
                channelWrite(_aggregate, last && len == 0);
```

Where `_channel.getResponse().isAllContentWritten(written);` is implemented like this:

```java
return (_contentLength >= 0 && written >= _contentLength);
```

So if you specify the content length beforehand it does not write everything into a giant buffer, but writes to a small aggregate buffer and flushes this periodically until the specified content length is reached.

`ThreadLocal` is as sweet trick for microbenchmarks with constant size, but I personally would not want to use it on a production server. If for any reason (malicous actor, bug in code) a big enough response is written, the RAM usage of that server is messed up until the server gets restarted.

I still think that the Rocker team have a really nice solution going with their CHUNKED solution :-)

**Comment by agentgt** [comment]
Yes but it is still buffering and often the buffers are the same size as the HTML. 
Remember you already have the data in memory! Just because it is an array list with a couple of pointers of header and footer does jack shit for memory saving because it is still going to be copied over and over. 

It would only matter for very large responses because HTML pages are often less than buffer size.

And Jetty is mostly blocking so but I'm fairly sure if you are going down the performance route you are going to turn on higher buffering.

> So if you specify the content length beforehand it does not write everything into a giant buffer, but writes to a small aggregate buffer and flushes this periodically until the specified content length is reached

Obviously if it is too big it isn't going to make a giant array. Tomcat will make temp files, Jetty I suppose blocks I admit I mainly focused on Netty and Undertow as Jetty typically underperforms on the ultra benchmarking scheme.

BESIDES you already have written it to a giant buffer! It just uses ArrayList instead of an array. You are basically hoping that the users content will be way less than the static content which is naive. Once you start adding i18n most of the template content will be dynamic.

Besides can we agree that you are going to at least copy the data once?

With the byte array approach you can avoid the extra buffers and cpu involved in that. Obviously it is a bad idea if your data is big BUT SO IS IT WITH CHUNKED!

> I still think that the Rocker team have a really nice solution going with their CHUNKED solution :-)

Literally no one uses it correctly. Go look at original ArraysofArrays code. It requires uses ReadableChannel. Otherwise you are copying the data over and over again.

Actually you are copying it when you do ReadableChannel its just that at least it is nonblocking and you can do backpressure. Let me ask as question. When you write to an OutputStream do you think the client gets the data immediately? No there is buffering or worse blocking. That is why some times web servers make temp files because if it is really big they can do zero copy from the operating system albeit I don't think netty or undertow does that (tomcat does I think).

Anyway go look at how Spring Webflux works. They want you to use their Data Buffer factory. Same with Netty, same with undertow. You can write to it like an OutputStream or just hand it a ByteBuffer aka byte array.

That is why I chose the byte array approach for high performance. Yes it has shit loads of caveats but the caveats are mostly the same as chunked.

EDIT: I should have added the other reason I chose the ARRAY approach is Jooby only allows returning a `byte[]` array for its template engine. 

It is not the only one that does that.

**Comment by agentgt** [comment]
Anyway here is the results for an Oracle ARM 4 core OCI machine free tier running in docker via `docker.sh`:

https://www.oracle.com/cloud/free/


```
Benchmark                     (output)   Mode  Cnt       Score       Error  Units
JStachioUtf8.benchmark           ARRAY  thrpt    3  245222.327 ± 27595.939  ops/s
JStachioUtf8.benchmark           CHUNK  thrpt    3  215201.078 ± 23406.272  ops/s
JteUtf8.benchmark                ARRAY  thrpt    3  221739.823 ± 25393.554  ops/s
JteUtf8.benchmark                CHUNK  thrpt    3  206973.901 ± 36094.766  ops/s
RockerUtf8.benchmark             ARRAY  thrpt    3  228476.109 ±  8802.170  ops/s
RockerUtf8.benchmark             CHUNK  thrpt    3  199463.946 ± 60802.340  ops/s
StringGetBytesUtf8.benchmark       N/A  thrpt    3  183752.509 ± 33630.014  ops/s
```

ascii

```
Benchmark                     (output)   Mode  Cnt       Score       Error  Units
JStachioUtf8.benchmark           ARRAY  thrpt    3  290674.908 ± 31211.804  ops/s
JStachioUtf8.benchmark           CHUNK  thrpt    3  254563.016 ± 37374.919  ops/s
JteUtf8.benchmark                ARRAY  thrpt    3  264876.374 ± 39256.221  ops/s
JteUtf8.benchmark                CHUNK  thrpt    3  247154.586 ±  4559.374  ops/s
RockerUtf8.benchmark             ARRAY  thrpt    3  234138.432 ± 80592.205  ops/s
RockerUtf8.benchmark             CHUNK  thrpt    3  243912.422 ± 35875.552  ops/s
StringGetBytesUtf8.benchmark       N/A  thrpt    3  330658.080 ± 34905.529  ops/s
```

I'll try the free AMD they provide next.

```
$ lscpu
Architecture:            aarch64
  CPU op-mode(s):        32-bit, 64-bit
  Byte Order:            Little Endian
CPU(s):                  4
  On-line CPU(s) list:   0-3
Vendor ID:               ARM
  Model name:            Neoverse-N1
    Model:               1
    Thread(s) per core:  1
    Core(s) per cluster: 4
    Socket(s):           -
    Cluster(s):          1
    Stepping:            r3p1
    BogoMIPS:            50.00
    Flags:               fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asim
                         ddp ssbs
NUMA:
  NUMA node(s):          1
  NUMA node0 CPU(s):     0-3
Vulnerabilities:
  Itlb multihit:         Not affected
  L1tf:                  Not affected
  Mds:                   Not affected
  Meltdown:              Not affected
  Mmio stale data:       Not affected
  Retbleed:              Not affected
  Spec store bypass:     Mitigation; Speculative Store Bypass disabled via prctl
  Spectre v1:            Mitigation; __user pointer sanitization
  Spectre v2:            Mitigation; CSV2, BHB
  Srbds:                 Not affected
  Tsx async abort:       Not affected
```

**Comment by agentgt** [comment]
OCI AMD free tier with docker image (I think the AMD is sort of free for limited time)


```
Benchmark                     (output)   Mode  Cnt       Score       Error  Units
JStachioUtf8.benchmark           ARRAY  thrpt    3  204846.435 ±  4222.513  ops/s
JStachioUtf8.benchmark           CHUNK  thrpt    3  173068.610 ± 15969.986  ops/s
JteUtf8.benchmark                ARRAY  thrpt    3  182185.673 ± 10966.240  ops/s
JteUtf8.benchmark                CHUNK  thrpt    3  153040.590 ± 24279.421  ops/s
RockerUtf8.benchmark             ARRAY  thrpt    3  197208.086 ±  9379.123  ops/s
RockerUtf8.benchmark             CHUNK  thrpt    3  172499.188 ± 25426.320  ops/s
StringGetBytesUtf8.benchmark       N/A  thrpt    3  145602.640 ±  3536.350  ops/s
```

ascii

```
Benchmark                     (output)   Mode  Cnt       Score       Error  Units
JStachioUtf8.benchmark           ARRAY  thrpt    3  248882.467 ±  5165.720  ops/s
JStachioUtf8.benchmark           CHUNK  thrpt    3  202081.356 ± 33166.630  ops/s
JteUtf8.benchmark                ARRAY  thrpt    3  226311.230 ± 50494.212  ops/s
JteUtf8.benchmark                CHUNK  thrpt    3  181389.436 ± 22238.489  ops/s
RockerUtf8.benchmark             ARRAY  thrpt    3  231459.818 ± 14254.960  ops/s
RockerUtf8.benchmark             CHUNK  thrpt    3  191145.417 ± 14571.447  ops/s
StringGetBytesUtf8.benchmark       N/A  thrpt    3  275450.979 ± 15131.379  ops/s
```

```
$ lscpu
Architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         40 bits physical, 48 bits virtual
  Byte Order:            Little Endian
CPU(s):                  4
  On-line CPU(s) list:   0-3
Vendor ID:               AuthenticAMD
  Model name:            AMD EPYC 7J13 64-Core Processor
    CPU family:          25
    Model:               1
    Thread(s) per core:  2
    Core(s) per socket:  2
    Socket(s):           1
    Stepping:            1
    BogoMIPS:            5090.43
    Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm rep_good n
                         opl cpuid extd_apicid tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hyperv
                         isor lahf_lm cmp_legacy cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw topoext perfctr_core ssbd ibrs ibpb stibp vmmcall fsgsbase tsc_adjust bmi1 avx2
                         smep bmi2 rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves clzero xsaveerptr wbnoinvd arat umip vaes vpclmulqdq rdpid arch_capabilities
Virtualization features:
  Hypervisor vendor:     KVM
  Virtualization type:   full
Caches (sum of all):
  L1d:                   128 KiB (2 instances)
  L1i:                   128 KiB (2 instances)
  L2:                    1 MiB (2 instances)
  L3:                    16 MiB (1 instance)
NUMA:
  NUMA node(s):          1
  NUMA node0 CPU(s):     0-3
Vulnerabilities:
  Itlb multihit:         Not affected
  L1tf:                  Not affected
  Mds:                   Not affected
  Meltdown:              Not affected
  Mmio stale data:       Not affected
  Retbleed:              Not affected
  Spec store bypass:     Mitigation; Speculative Store Bypass disabled via prctl and seccomp
  Spectre v1:            Mitigation; usercopy/swapgs barriers and __user pointer sanitization
  Spectre v2:            Mitigation; Retpolines, IBPB conditional, IBRS_FW, STIBP conditional, RSB filling, PBRSB-eIBRS Not affected
  Srbds:                 Not affected
  Tsx async abort:       Not affected
```

**Comment by casid** [comment]
You know that arguing with you is extremly frustrating? You just spill out a bunch of half guessed assumptions how things work (chunked encoding, temp files, jada jada).

Since you (like I did) copied the idea of binary rendering from Rocker, at least try to appreciate their idea behind it: https://github.com/fizzed/rocker#near-zero-copy-rendering

And I get that you tweaked the Jooby techempower benchmarks, but since it only allowed to pass a byte array you didn't get a chance to explore other options, no?

Since you mentioned `ArrayOfByteArrays`, please appreciate the Javadoc of `toByteArray`:

```
/**
     * Expensive operation of allocating a byte array to hold the entire contents
     * of this output and then copying each underlying byte array into this new
     * byte array.  Lots of memory copying...
     * 
     * @return A new byte array
     */
    public byte[] toByteArray() {
        byte[] bytes = new byte[this.byteLength];
        int offset = 0;
        for (byte[] chunk : arrays) {  
            System.arraycopy(chunk, 0, bytes, offset, chunk.length);
            offset += chunk.length;
        }
        return bytes;
    }
```

That's my point. You're benchmarking something that was never meant to produce entire byte arrays.

**Comment by agentgt** [comment]
> You know that arguing with you is extremly frustrating? 

I'm very sorry. I was in a rush. I meant to double check all my claims and reference them and I got carried away. I come off as crude at times but honestly I appreciate the back and forth.

I'm also equally frustrated. Like you brought TCP packets when we are talking about HTTP... through a framework... that provides very different abstractions.

> That's my point. You're benchmarking something that was never meant to produce entire byte arrays.

How else am I going to test it? How am I going to get the data out? Would you like me to pass `ByteArrayOutputStream`?

The benchmark requires returning something but I can make it void I suppose. That is just testing putting data in whatever format but in the real world it has to be pulled out.

Out of curiosity I will try not doing any toByteArray() in the benchmarks to see what happens.

> I still think that the Rocker team have a really nice solution going with their CHUNKED solution :-)
>> Literally no one uses it correctly. Go look at original ArraysofArrays code. It requires uses ReadableChannel. Otherwise you are copying the data over and over again.

Ideally I would test in Rocker's ReadableChannel. I assume you saw that below it. That is the only way to avoid sort of not copying. Its kind of annoying because I mentioned it if you looked at the code and then you put in what I already referenced over and over.

https://github.com/fizzed/rocker/blob/d749fbf68179b31a64d541f5e18e0e25bc5c2d1b/rocker-runtime/src/main/java/com/fizzed/rocker/runtime/ArrayOfByteArraysOutput.java#L110

However your implementation does not have that last I checked. Do you know why that makes a difference? It is because the consumer is providing the buffer and the producer (template-engine) knows how much it can fill up the buffer. It is a pull model. OutputStream is a push model. 

Also if you can show me a web-framework or webserver that takes ReadableChannel as a result I will look how they do the extraction to mimic it and update the benchmark. I was going to use Reactive Streams publisher as overkill but not enough time. BTW the same algorithm to convert the array list into a ReadableChannel is basically the same for an array.

So I basically just normalized the extraction on all the algorithms to a byte array. Feel free to come up with something better.

I don't discount Rocker for coming up with pre-encoding and I think Chunked clearly kicks ass for Windows. My question is it the right solution for high performance usually linux server?

Did someone actually test this.

Lets go over how this is supposed to work for say a blocking server:

* Template Engine executes and creates a CHUNK or ARRAY output. 
* For the blocking case we now copy those results to lets say `OutputStream`

Now lets say I use the ARRAY approach:

```java
outputStream.write(ARRAY.getByteArray(), 0, ARRAY.size()); // we get the actual buffer not toByteArray()
```

Here is the CHUNKED approach

```java
for (var array: CHUNKED.arrays()) {
  outputStream.write(array);
}
```

Now I don't have benchmarks for the exact code above but I have a strong idea of what is probably faster.

That is for the blocking case which is the Jetty example.

For nonblocking it gets complicated because nonblocking usually gives you a buffer factory which is all over the place on interface contracts. To be frank I'm not sure how I could test that well with JMH across the engines.

Anyway I apologize on being crude.

**Comment by casid** [comment]
I'm sorry for being rude as well. I think we really talked past each other.

> How else am I going to test it?

Testing this would require an application server and then firing lots of request at it, like techempower style. Which is pretty hard to do, because now we don't test the template engine in isolation but the entire stack. I'm sorry that I came over as I had a perfect solution for this, I was just trying to make the point that Rocker tried to optimize for the whole stack, which is really hard to test. For this JMH micro benchmark you absolutely picked the right approach with the byte array.

> However your implementation does not have that last I checked.

I'm sorry that I glossed over it. You are right, my implementation does not have this. And of course you are correct, it will push the entire amount of bytes into the `OutputStream`, so fast that the underlying server needs to buffer everything anyways. I'll have a look at `ReadableChannel`. Currently this is a footgun in my API and having a byte array would be better.

So far I haven't seriously used any nonblocking webservers, so I have no idea how it would work there.

Thanks for the explanation!

**Comment by agentgt** [comment]
EDIT disregard. I didn't see your update.

> You just spill out a bunch of half guessed assumptions how things work (chunked encoding, temp files, jada jada).

Please point out my mistakes or what I mis-claimed. Honestly I want to improve. For a lot servers if you do not set the content-length, chunked encoding will be turned on. I will double check with Jetty later. As for the temp files I will have to pull up the Tomcat code that does this. My point was about blocking. You either buffer or block because of the push nature.

When you call an `OutputStream.write` you would think it would just write to the socket right. I assume that was your TCP argument. Well most web frameworks do not use sockets anymore but NIO.

There is inherent buffering like your Jetty linked coded shows.

What happens when a webframeworks `OutputStream` gets a write call?

You either:

 * fill a buffer (usually bytebuffer which might get sent or partial sent)
 * block because can't fill any buffer
 * or fail

Basically you are constantly copying. 

When you call `write` with varying data and the buffer size is too small the web server OutputStream has to do a lot of work and more write calls mean more work. Going back and forth splitting/growing buffers and taking subsets to fill an existing partial buffer etc.

However if we have an entire `ByteBuffer` or `byte[]` (ARRAY) you can call Jetty's `sendContent(ByteBuffer buffer)` or better for CHUNKED it has apparently a `sendContent(ReadableChannel)` which I was unaware of. With a byte array / buffer it knows the entire size so that is an advantage.

I suppose I could try to construct a test with some `ReadableChannel` later.

Anyway I'm sorry about earlier.

**Comment by casid** [comment]
> Please point out my mistakes or what I mis-claimed.

> And while the OutputStream (which requires set content-length first which requires buffering anyway!) is the common denominator for blocking algorithms it is not for non-blocking. Besides most of the frameworks turn it back into byte array otherwise it becomes Transfer-Encoding: chunked encoding which is highly discouraged for HTML output.

Was causing my rant (which I'm sorry about!). As far as I know, setting content-length does not necessarily mean buffering everything. The server should be able to send the content-length as part of the header, so that the client knows what to expect and then the server sends the body packets, but it does not need to hold the entire body in RAM already to do that. Again, sorry for ranting, it's been getting late and I couldn't sleep well.

> I suppose I could try to construct a test with some ReadableChannel later.

That'd be awesome! If you can pull this off, I'd be very curious to see this!

**Comment by agentgt** [comment]
I updated the benchmarks for `ReadableByteChannel`. It seems to equalize ARRAY and CHUNK. For all extensive purposes I agree we are now in the realm of micro optimization and more or less perf wise: 

* ARRAY = CHUNK
* JSTACHIO = JTE = ROCKER

You can click on the action artifacts and download the results and you will see how while the graphs appear to be different they vary across runs, platforms, output algorithm but not consistently and the error delta is greater than the differences.

I will update the readme based on the above that three top compile to Java template engines are basically equal which makes since.

My impetus (which I hope is mostly altruistic) for doing the output testing is because ideally as a template engine author integrating with web frameworks there should be a clear choice and there is not. If one engine finds the better output algorithm for a particularly framework the hope is that could be shared across all template engines that do pre-encoding (or not).

Just to give you an example of how the output algorithm differs see Spring's freemarker integration:

https://github.com/spring-projects/spring-framework/blob/0da224136792d928a255b56cc3dcdb8e2ea7666d/spring-webflux/src/main/java/org/springframework/web/reactive/result/view/freemarker/FreeMarkerView.java#L255

(`FastByteArrayOutputStream` is the DEQUE algorithm)

Compared to JStachio's which uses the builtin buffer factory directly:

https://github.com/jstachio/jstachio/blob/dc5af0e5807643dedbf0728e38b056babd5ae73b/opt/jstachio-spring-webflux/src/main/java/io/jstach/opt/spring/webflux/JStachioEncoder.java#L143

Which way is the correct way? If I want to port my integration work to Rocker and JTE or make some common abstraction they can use should I do it the way freemarker is doing it (DEQUE), or CHUNKED or should I just create a `byte[]` / `ByteBuffer` / `DataBuffer` directly (which is more or less ARRAY)?

Rocker's CHUNKED, and Spring's DEQUE have zero benchmarks that I could find so I can't just believe Rocker's claims that it is more performant or even zero copy.

So this isn't really about which template engine is fastest anymore but how to integrate. Perhaps at some point I can make a kind of mini techempower to test the full webstack using gatling or similar. 

> As far as I know, setting content-length does not necessarily mean buffering everything.

Yeah my wording was terrible on the comment and I totally can understand your frustration. What I meant about `content-length` is that the web server/framework may choose an appropriate *existing* buffer or if it is really large may buffer to a tmp file as I saw that with Tomcat sometime ago. I did not mean `byte[] buffer = new byte[content_length];`.

One of the limitations of `OutputStream` and `ReadableByteChannel` is that the total size is unknown which for some frameworks maybe useful because they can decide which buffers to reuse from the buffer pool. In theory for less copying it would be ideal to access the buffer pool directly.

For blocking Jetty this probably matters less and is not easy to access the buffer pool anyway from Jetty (you have to cast to get HttpOutput and then pull out HttpChannel which has the buffer pool).

Also direct `byte[]` allocation on linux like platforms seems to be faster than windows. I have a feeling windows probably yields better results when accessing the buffer pool directly since allocation is a little more expensive but take that as just a conjecture.

> but it does not need to hold the entire body in RAM already to do that.

Correct but for most cases it will effectively have the entire body in memory probably multiple times till GC happens. That is basically what I meant.

Anyway I'm truly indebted to all your work helping me! If you are ever in the Boston area let me know as I owe you greatly.

Cheers

**Pull request merged**
